name: Development Deployment

on: 
  push:
    branches:
      - development

env:
  ENVIRONMENT_VAR: ${{ vars.ENVIRONMENT_VAR }}

jobs:
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Unit Testing
              run: echo 'Unit testing completed! ✅'

    dev-deploy:
        needs: unit-test
        environment: development
        runs-on: ubuntu-latest
        steps:
            - name: Display environment variables
              run: echo $ENVIRONMENT_VAR
