name: Development Deployment

on: 
  push:
    branches:
      - development

env:
  SECRET_VALUE: ${{ secrets.TOP_SECRET_VALUE }}

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Unit Testing
              run: echo 'Unit testing completed! ✅'

    dev-deploy:
        environment: development
        runs-on: ubuntu-latest
        steps:
            - name: Display secret values
              run: echo $SECRET_VALUE
